---
title: "Data Tidying"
author: "Jeanette Clark"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F, message = F}
library(dplyr)
library(tidyr)
```


Data sourced from: Mike Byerly. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. [df35b.304.2](https://knb.ecoinformatics.org/#view/df35b.304.2)

```{r}
catch_original <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                  stringsAsFactors = FALSE)

region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"),
                        stringsAsFactors = FALSE) %>% 
    select(code, mgmtArea)
```

Fix an OCR error where a 1 was recorded as an I in the dataset, move from wide to long format, and convert catch column to be in number of fish.

```{r}
catch_long <- catch_original %>%
  select(-All, -notesRegCode) %>% 
  # change capital I to 1 because of OCR error
  mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>% 
  # coerce Chinook to numeric type
  mutate(Chinook = as.numeric(Chinook)) %>% 
  pivot_longer(-c(Region, Year), names_to = "species", values_to = "catch") %>%
  mutate(catch = catch*1000)

catch_joined <- left_join(catch_long, region_defs, by = c("Region" = "code"))
```

Calculate mean catch by region

```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch))

head(mean_region)
```

